babylonlabs-io/wallet-connector

.changeset/README.md
.changeset/breezy-penguins-cover.md
.github/workflows/ci.yml
tsconfig.app.json

1. Fixes the
```
Module '"/home/runner/work/bbn-wallet-connect/bbn-wallet-connect/node_modules/@types/long/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
```
2. Adds the CI that builds the project
3. Formats the codebase

fix: Build fix + format

---

.changeset/new-cats-remember.md
package-lock.json
package.json
vite.config.ts

Adds node polyfills. 
In our example `bitget` uses `Psbt` from `bitcoinjs-lib`. Without such polyfills running storybook will throw "Buffer is not defined"

feat: Node polyfills

---

.changeset/big-eggs-attack.md
src/core/types.ts
src/core/wallets/bbn/BBNProvider.ts
src/core/wallets/bbn/keplr/provider.ts

- Minimize Keplr interface
- Remove the Stargate client Keplr provider dependency. This is still an internal repository `npm` dependency as will be used later on in tests
- Returns the offline signer so the outside world (like `simple-staking`) can use it
- Adds `getWalletProviderName` and `getWalletProviderIcon`
Closes #55 and #63

feat: Keplr offline signer, minimize interface

---

.changeset/shy-poems-buy.md
src/core/types.ts

Leaves `ecdsa` as the only option in the provider

feat: ECDSA signMessage option

---

package-lock.json
src/components/TermsOfService/index.tsx
src/components/WalletProvider/index.stories.tsx

Adds 2 more stories:
- First shows the data from the both wallets https://i.imgur.com/Wpf3pDm.png
- Second allows our BTC wallet to `signPsbt` and `signMessage` https://i.imgur.com/PevsMTq.png https://i.imgur.com/djU9Ucj.png
Useful for manual testing wallets methods and properties
Keplr will be in another PR and not a priority as of today. Created an issue for that:
https://github.com/babylonlabs-io/bbn-wallet-connect/issues/142

feat: Connect stories

---

.changeset/lazy-wombats-turn.md
package-lock.json
package.json
src/core/wallets/btc/keystone/provider.ts

- Uses ecc lib from `btc-staking-ts`
- Updates keystone deps to latest so `simple-staking` can work once `tomo` updates
Closes #128

feat: Keystone - init ecc curve from btc-staking-ts, update deps

---

.changeset/serious-rabbits-brake.md
package-lock.json
vite.config.ts

Removes Keystone SDK out of `external` vite bundle to solve the issue linking with `simple-staking` Next.js
Supportive ticket for future: https://github.com/babylonlabs-io/bbn-wallet-connect/issues/150

feat: Keystone out of external

---

.changeset/rich-bottles-grab.md
package-lock.json
package.json

Storybook not building properly because of:
https://github.com/storybookjs/storybook/issues/30115
https://github.com/evanw/esbuild/issues/4010
https://github.com/evanw/esbuild/pull/4013
This PR overrides the version of `esbuild` to the latest working one

fix: Override esbuild version

---

.changeset/angry-spies-guess.md
README.md

Changes the link to an absolute one, so it's compatible across the devices

fix: GitHub Readme absolute link

---

.changeset/new-ants-trade.md
package-lock.json
package.json
vite.config.ts

Removes `@bitcoin-js/tiny-secp256k1-asmjs` as not using

feat: Remove tiny secp dependency

---

package-lock.json
package.json
src/components/ResponsiveDialog/ResponsiveDialog.tsx
src/components/WalletProvider/components/Screen.tsx
src/components/WalletProvider/components/WalletDialog.tsx
src/hooks/useIsMobileView.ts

https://github.com/user-attachments/assets/f846e2de-f39e-478e-a981-730819ee4db7
Given we don't have much time for this task, I made a lot short-cut here.
To do it properly:
* Move `ResponsiveDialog` to core-ui library so that it can be shared to other libs.
* Move the screen breakpoint to a shared library
* MobileDialog from core-ui needs some rework, it doesn't work well with small mobile size in story book.

make connect component mobile compatible

---

.changeset/chilly-fans-cross.md
package-lock.json
package.json

Bumps `btc-staking-ts` to `0.4.0-canary.10`.

feat: Bump btc-staking-ts

---

.changeset/famous-buttons-protect.md
src/core/wallets/btc/unisat/provider.ts

Unisat uses `removeListener` instead of `off`
Partly closes https://github.com/babylonlabs-io/babylon-wallet-connector/issues/188

feat: Unisat - accountsChanged removeListenet

---

.changeset/fast-radios-march.md
.changeset/unlucky-seas-listen.md
src/core/wallets/btc/okx/provider.ts
src/core/wallets/btc/onekey/provider.ts

Remove `accountsChanged ` event from OneKey. Only `accountChanged` is used
Partly closes https://github.com/babylonlabs-io/babylon-wallet-connector/issues/188

feat: OneKey account change

---

.changeset/late-melons-swim.md
README.md
src/core/types.ts
src/core/wallets/bbn/keplr/provider.ts
src/core/wallets/bbn/leap/provider.ts
src/core/wallets/bbn/okx/provider.ts

`OfflineAminoSigner & OfflineDirectSigner` -> `OfflineAminoSigner | OfflineDirectSigner`. Compatible with `import { OfflineSigner } from "@cosmjs/proto-signing";` 
So if wallet thinks `OfflineAminoSigner` signer should be used, it returns it. If `Direct` is enough - returns `OfflineDirectSigner`.
Note: we are offloading this to the wallet itself, and not using `if account.isNanoLedger` or whatever, since these flags can change
Current approach in this PR works on both Keplr and Leap. OKX does not allow Ledger Cosmos connection.

feat: Offline Signer Auto

---

.changeset/empty-tomatoes-suffer.md
README.md
src/core/types.ts
src/core/wallets/bbn/keplr/provider.ts
src/core/wallets/bbn/leap/provider.ts
src/core/wallets/bbn/okx/provider.ts

- Adds `on` and `off` events for `cosmos` wallets, similar to `bitcoin` wallets
- Attaches to the proper window `event`
- `OKX` is not there yet, but the assumption is made
- In case they change the naming to something different, this particular string can be changed
- Update the interface and Readme
- Outside usage is the same as for `btc` wallets - `accountChange` event
Closes #260

feat: Babylon Cosmos wallets onChange

---

.changeset/wise-lamps-begin.md
src/components/WalletProvider/index.stories.tsx
src/core/wallets/btc/keystone/provider.ts

Adds a support of `bip322-simple` and `ecdsa` via Keystone
Closes #273

feat: Keystone BIP322 + ECDSA support

---

README.md
src/core/types.ts
src/core/wallets/btc/unisat/provider.ts

Adds an information about the signing contract. Right now works on the BTC Mainnet only.
UI:
Closes #352 
`simple-staking` usage draft PR: https://github.com/babylonlabs-io/simple-staking/pull/923

feat: Unisat contract

---

package-lock.json
package.json

Updates `btc-staking-ts` to `1.0.9` - no `peerDependencies` are used

fix: update btc-staking-ts peer dependencies

---

package-lock.json
package.json

It seems to me that we can move `btc-staking-ts` to dev deps. Wallets shouldn't be responsible for init of BTCCurve

feat: update btc-staking-ts
